dist: xenial
language: node_js
sudo: required

addons:
  apt:
    packages:
      - rabbitmq-server

branches:
  only:
    - master

services:
  - rabbitmq
  - docker
  - mongodb

install:
  - npm run clean
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 8"
      node_js: 8

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 10"
      node_js: 10

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls
        
    - stage: test
      name: "Unit Tests: Node 12"
      node_js: 12

      before_install:
        - docker pull ansi/mosquitto
        - docker run -d -p 1883:1883 -l mosquitto ansi/mosquitto

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      node_js: 10

      script:
        - npm run lint:md
        - npm run lint:text
